# Datenstrom Yellow extension settings

Extension: Cards
Version: 0.2.2
Description: Make cards from pages and their settings.
Developer: Liam Perlaki
Tag: feature
DownloadUrl: https://github.com/pfadfinder26/yellow-cards/archive/refs/heads/main.zip
DocumentationUrl: https://github.com/pfadfinder26/yellow-cards
DocumentationLanguage: en, de
Published: 2026-09-28 12:31:36
Status: experimental
system/workers/cards.php: cards.php, create, update
system/layouts/card-default.html: card-default.html, create, update, careful
